### ISSUE TITLE
Some praise

### ISSUE THREAD

**Issue by xandark** [StewBC/mminer-apple2#1]
Just wanted to say thank you for sharing this. I've heard about this game in legendary tones from Spectrum users and never got a chance to play it. I like how you solved the resolution difference. I honestly don't notice the scrolling to "catch up" the viewport around the player, it's that good.

Maybe I'll figure it out in time, though after about 5 minutes, I can't seem to figure out how to get past the red guy on the first screen, I don't know what the purple structure does at the bottom right corner of the screen, and found I could focus better with the music off, which is not a knock against what you've done at all, it was that way in the 80's and we loved it :)

**Comment by StewBC** [comment]
Hi,

Thank you for the very nice note!  Greatly appreciated :)

The purple block in the lower right is the door.  It will flash once you have all the keys and then you exit to the next stage by walking into it.

If you get stuck and you feel like having a look at how it "should" be done, you can check out this video: https://www.youtube.com/watch?v=BgUzteADsRI

Thanks again for the nice note :)

All the best,
Stefan
On 4/27/2020 1:30:54 PM, xandark <notifications@github.com> wrote:
Just wanted to say thank you for sharing this. I've heard about this game in legendary tones from Spectrum users and never got a chance to play it. I like how you solved the resolution difference. I honestly don't notice the scrolling to "catch up" the viewport around the player, it's that good.
Maybe I'll figure it out in time, though after about 5 minutes, I can't seem to figure out how to get past the red guy on the first screen, I don't know what the purple structure does at the bottom right corner of the screen, and found I could focus better with the music off, which is not a knock against what you've done at all, it was that way in the 80's and we loved it :)
